name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Semantic Version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Initializing logging..."
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finishing logging..."
        echo "new release version: $NEW_VERSION"

    # - name: Build Docker Image
    #   run: |
    #     docker build -t elvisss24/docker-graphql:0.0.2 .
    #     docker build -t elvisss24/docker-graphql:latest .

    # - name: Push Docker Image
    #   run: |
    #     docker push elvisss24/docker-graphql:0.0.2
    #     docker push elvisss24/docker-graphql:latest
